version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file sampleTemplate.yaml --s3-bucket codepipeline-artifacts-st3523 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml